# Generated by Django 4.2.30 on 2026-07-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_book_title_devanagari_book_title_iast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sutra',
            name='item_label',
            field=models.CharField(default='Sūtra', max_length=100),
        ),
        migrations.AddField(
            model_name='sutra',
            name='item_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
