# Generated by Django 4.2.30 on 2026-07-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_sutra_item_label_sutra_item_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='source_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='source_text_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
