# Generated by Django 4.2.30 on 2026-07-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_note_source_text_note_source_text_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Personal commentary or observations (Markdown supported)'),
        ),
    ]
